server:
  port: 8000
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
security:
  basic:
    enabled: true
  user:
    #这是config-server的用户名和密码
    name: root
    password: 123456