spring:
  application:
    name: springcloud-zipkin-config
server:
  port: 8003
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:8000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}