spring:
  application:
    name: springcloud-provider-config111
  zipkin:
    base-url: http://localhost:8003
  sleuth:
    sampler:
      percentage: 1.0
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:8000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    appname: springcloud-provider-config123